{
 "title": "Kubernetes / Autoscaling / Cluster Autoscaler",
 "description": "A dashboard that monitors the Cluster Autoscaler. The dashboards were generated using [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "cluster-autoscaler"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info{job=~\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cluster_autoscaler_last_activity{cluster=\"$cluster\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "description": "The total number of nodes in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_nodes_count{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Max Nodes",
   "type": "stat",
   "description": "The maximum number of nodes allowed in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_max_nodes_count{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Node Groups",
   "type": "stat",
   "description": "The number of node groups in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_node_groups_count{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Healthy Nodes",
   "type": "gauge",
   "description": "The percentage of healthy nodes in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_nodes_count{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\n      state=\"ready\"\n    }\n  ) /\n  sum(\n    cluster_autoscaler_nodes_count{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  ) * 100\n)\n"
    }
   ]
  },
  {
   "title": "Safe to Scale",
   "type": "stat",
   "description": "Indicates whether it is safe to scale the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  cluster_autoscaler_cluster_safe_to_autoscale{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Unscheduled Pods",
   "type": "stat",
   "description": "The number of unscheduled pods in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_unschedulable_pods_count{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Last Scale Down",
   "type": "stat",
   "description": "The timestamp of the last scale down activity.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max(\n  cluster_autoscaler_last_activity{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    activity=\"scaleDown\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Last Scale Up",
   "type": "stat",
   "description": "The timestamp of the last scale up activity.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max(\n  cluster_autoscaler_last_activity{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    activity=\"scaleUp\"\n  }\n)\n"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Pod Activity",
   "type": "timeseries",
   "description": "The activity of pods in the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      cluster_autoscaler_unschedulable_pods_count{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  ) by (type)\n)\n",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "round(\n  sum(\n    increase(\n      cluster_autoscaler_evicted_pods_total{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  ) by (eviction_result)\n)\n",
     "legendFormat": "Evicted / {{ eviction_result }}"
    }
   ]
  },
  {
   "title": "Node Activity",
   "type": "timeseries",
   "description": "The activity of nodes in the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_nodes_count{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  ) by (state)\n)\n",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Autoscaling Activity",
   "type": "timeseries",
   "description": "The autoscaling activity in the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_nodes_count{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  )\n)\n",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_unneeded_nodes_count{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  )\n)\n",
     "legendFormat": "Unneeded"
    },
    {
     "expr": "round(\n  sum(\n    increase(\n      cluster_autoscaler_scaled_up_nodes_total{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Scaled Up"
    },
    {
     "expr": "round(\n  sum(\n    increase(\n      cluster_autoscaler_scaled_down_nodes_total{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "Scaled Down"
    }
   ]
  },
  { "title": "Node Group Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "The total number of node groups in the cluster.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  cluster_autoscaler_node_group_min_count{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "At Capacity",
   "type": "gauge",
   "description": "The percentage of node groups at capacity.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  count(\n    (\n      avg by (node_group) (\n        cluster_autoscaler_node_group_target_count{\n          cluster=\"$cluster\",\njob=~\"$job\"\n\n        }\n      ) /\n      max by (node_group) (\n        cluster_autoscaler_node_group_max_count{\n          cluster=\"$cluster\",\njob=~\"$job\"\n\n        }\n      )\n    ) >= 0.99\n  ) /\n  count(\n    cluster_autoscaler_node_group_max_count{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  ) * 100\n) or vector(0)\n"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "gauge",
   "description": "The percentage of healthy node groups in the cluster.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_node_group_healthiness{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  ) /\n  count(\n    cluster_autoscaler_node_group_healthiness{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  ) * 100\n)\n"
    }
   ]
  },
  {
   "title": "Backoff",
   "type": "gauge",
   "description": "The percentage of node groups in backoff state.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_node_group_backoff_status{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  ) /\n  count(\n    cluster_autoscaler_node_group_backoff_status{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  ) * 100\n)\n"
    }
   ]
  },
  {
   "title": "Node Group Details",
   "type": "table",
   "description": "Details of node groups in the cluster. Requires --emit-per-nodegroup-metrics flag.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min by (node_group) (\n  cluster_autoscaler_node_group_min_count{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n)\n"
    },
    {
     "expr": "avg by (node_group) (\n  cluster_autoscaler_node_group_target_count{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n)\n"
    },
    {
     "expr": "max by (node_group) (\n  cluster_autoscaler_node_group_max_count{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n)\n"
    },
    {
     "expr": "min by (node_group) (\n  cluster_autoscaler_node_group_healthiness{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n)\n"
    },
    {
     "expr": "max by (node_group) (\n  cluster_autoscaler_node_group_backoff_status{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n)\n"
    }
   ]
  }
 ]
}