{
 "title": "Kubernetes / Autoscaling / Pod Disruption Budget",
 "description": "A dashboard that monitors Kubernetes and focuses on giving a overview for pod disruption budgets. The dashboards were generated using [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "kubernetes-core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info{job=~\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kube_poddisruptionbudget_status_current_healthy{cluster=\"$cluster\"}, job)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_poddisruptionbudget_status_current_healthy{cluster=\"$cluster\", job=~\"$job\"}, namespace)"
   },
   {
    "name": "poddisruptionbudget",
    "label": "Pod Disruption Budget",
    "query": "label_values(kube_poddisruptionbudget_status_current_healthy{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$namespace\"}, poddisruptionbudget)"
   }
  ]
 },
 "panels": [
  { "title": "$namespace Namespace Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Summary",
   "type": "table",
   "description": "Summary of all PDBs in the selected namespace.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_pod_disruptions_allowed{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n\n    }\n  ) by (job, namespace, poddisruptionbudget)\n)\n"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_desired_healthy{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n\n    }\n  ) by (job, namespace, poddisruptionbudget)\n)\n"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_current_healthy{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n\n    }\n  ) by (job, namespace, poddisruptionbudget)\n)\n"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_expected_pods{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n\n    }\n  ) by (job, namespace, poddisruptionbudget)\n)\n"
    }
   ]
  },
  { "title": "$poddisruptionbudget", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "poddisruptionbudget" },
  {
   "title": "Disruptions Allowed",
   "type": "stat",
   "description": "The number of pod disruptions allowed for the selected PDB.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_pod_disruptions_allowed{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\npoddisruptionbudget=~\"$poddisruptionbudget\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Desired Healthy",
   "type": "stat",
   "description": "The desired number of healthy pods for the selected PDB.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_desired_healthy{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\npoddisruptionbudget=~\"$poddisruptionbudget\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Currently Healthy",
   "type": "stat",
   "description": "The current number of healthy pods for the selected PDB.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_current_healthy{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\npoddisruptionbudget=~\"$poddisruptionbudget\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Expected Pods",
   "type": "stat",
   "description": "The expected number of pods for the selected PDB.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_expected_pods{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\npoddisruptionbudget=~\"$poddisruptionbudget\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "description": "Status metrics for the selected PDB over time.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_pod_disruptions_allowed{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\npoddisruptionbudget=~\"$poddisruptionbudget\"\n\n    }\n  )\n)\n",
     "legendFormat": "Disruptions Allowed"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_desired_healthy{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\npoddisruptionbudget=~\"$poddisruptionbudget\"\n\n    }\n  )\n)\n",
     "legendFormat": "Desired Healthy"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_current_healthy{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\npoddisruptionbudget=~\"$poddisruptionbudget\"\n\n    }\n  )\n)\n",
     "legendFormat": "Currently Healthy"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_expected_pods{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\npoddisruptionbudget=~\"$poddisruptionbudget\"\n\n    }\n  )\n)\n",
     "legendFormat": "Expected Pods"
    }
   ]
  }
 ]
}