{
 "title": "Kubernetes / Autoscaling / Horizontal Pod Autoscaler",
 "description": "A dashboard that monitors Horizontal Pod Autoscalers. The dashboards were generated using [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "kubernetes-core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info{job=~\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kube_horizontalpodautoscaler_spec_target_metric{cluster=\"$cluster\"}, job)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_horizontalpodautoscaler_spec_target_metric{cluster=\"$cluster\", job=~\"$job\"}, namespace)"
   },
   {
    "name": "horizontalpodautoscaler",
    "label": "HPA",
    "query": "label_values(kube_horizontalpodautoscaler_spec_target_metric{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$namespace\"}, horizontalpodautoscaler)"
   },
   {
    "name": "metric_name",
    "label": "Metric Name",
    "query": "label_values(kube_horizontalpodautoscaler_spec_target_metric{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", horizontalpodautoscaler=~\"$horizontalpodautoscaler\"}, metric_name)"
   },
   {
    "name": "metric_target_type",
    "label": "Metric Target Type",
    "query": "label_values(kube_horizontalpodautoscaler_spec_target_metric{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$namespace\", horizontalpodautoscaler=~\"$horizontalpodautoscaler\", metric_name=~\"$metric_name\"}, metric_target_type)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "description": "The desired number of replicas for the HPA.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_status_desired_replicas{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "description": "The current number of replicas for the HPA.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_status_current_replicas{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "stat",
   "description": "The minimum number of replicas configured for the HPA.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_spec_min_replicas{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "stat",
   "description": "The maximum number of replicas configured for the HPA.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_spec_max_replicas{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Metric Targets",
   "type": "table",
   "description": "Configured metric targets for the HPA.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_horizontalpodautoscaler_spec_target_metric{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n,\nmetric_name=~\"$metric_name\"\n\n  }\n) by (job, namespace, horizontalpodautoscaler, metric_name, metric_target_type)\n"
    }
   ]
  },
  {
   "title": "$horizontalpodautoscaler / $metric_name / $metric_target_type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "metric_target_type"
  },
  {
   "title": "Usage & Threshold",
   "type": "timeseries",
   "description": "The current utilization and configured threshold for the HPA metric.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_horizontalpodautoscaler_status_target_metric{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n,\nmetric_name=~\"$metric_name\"\n,\nmetric_target_type=~\"$metric_target_type\"\n\n  }\n) by (job, namespace, horizontalpodautoscaler, metric_name, metric_target_type)\n",
     "legendFormat": "{{ metric_target_type }} / {{ metric_name }}"
    },
    {
     "expr": "sum(\n  kube_horizontalpodautoscaler_spec_target_metric{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n,\nmetric_name=~\"$metric_name\"\n,\nmetric_target_type=~\"$metric_target_type\"\n\n  }\n) by (job, namespace, horizontalpodautoscaler, metric_name, metric_target_type)\n",
     "legendFormat": "Threshold / {{ metric_name }}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "description": "The desired, current, minimum, and maximum replicas for the HPA over time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_status_desired_replicas{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n\n    }\n  )\n)\n",
     "legendFormat": "Desired Replicas"
    },
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_status_current_replicas{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n\n    }\n  )\n)\n",
     "legendFormat": "Current Replicas"
    },
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_spec_min_replicas{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n\n    }\n  )\n)\n",
     "legendFormat": "Min Replicas"
    },
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_spec_max_replicas{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$namespace\"\n,\nhorizontalpodautoscaler=~\"$horizontalpodautoscaler\"\n\n    }\n  )\n)\n",
     "legendFormat": "Max Replicas"
    }
   ]
  }
 ]
}