{
 "title": "Kubernetes / Autoscaling / Karpenter / Performance",
 "description": "A dashboard that monitors Karpenter performance metrics. The dashboards were generated using [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "karpenter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(karpenter_nodes_allocatable, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster State Synced",
   "type": "stat",
   "description": "Indicates whether the cluster state is synced.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_cluster_state_synced{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n) by (job)\n"
    }
   ]
  },
  {
   "title": "Cluster State Node Count",
   "type": "stat",
   "description": "The number of nodes in the cluster state.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_cluster_state_node_count{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n) by (job)\n"
    }
   ]
  },
  {
   "title": "Cloud Provider Errors",
   "type": "timeseries",
   "description": "The number of cloud provider errors over time.",
   "gridPos": { "h": 6, "w": 18, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      karpenter_cloudprovider_errors_total{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  ) by (job, provider, controller, method, error)\n)\n",
     "legendFormat": "{{ provider }} - {{ controller }} - {{ method }} - {{ error }}"
    }
   ]
  },
  {
   "title": "Node Termination Duration",
   "type": "timeseries",
   "description": "The duration to terminate nodes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n  karpenter_nodes_termination_duration_seconds{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    quantile=\"0.5\"\n  }\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "max(\n  karpenter_nodes_termination_duration_seconds{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    quantile=\"0.95\"\n  }\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "max(\n  karpenter_nodes_termination_duration_seconds{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    quantile=\"0.99\"\n  }\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Pods Startup Duration",
   "type": "timeseries",
   "description": "The duration for pods to start up.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n  karpenter_pods_startup_duration_seconds{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    quantile=\"0.5\"\n  }\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "max(\n  karpenter_pods_startup_duration_seconds{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    quantile=\"0.95\"\n  }\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "max(\n  karpenter_pods_startup_duration_seconds{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    quantile=\"0.99\"\n  }\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Scheduler Queue Depth",
   "type": "timeseries",
   "description": "The number of pending pods waiting to be scheduled.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_scheduler_queue_depth{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n) by (job)\n",
     "legendFormat": "Queue Depth"
    }
   ]
  },
  {
   "title": "Scheduler Scheduling Duration",
   "type": "timeseries",
   "description": "The duration to simulate pod scheduling.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    rate(\n      karpenter_scheduler_scheduling_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    rate(\n      karpenter_scheduler_scheduling_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    rate(\n      karpenter_scheduler_scheduling_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Interruption Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Interruption Received Messages",
   "type": "timeseries",
   "description": "The number of interruption messages received.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    karpenter_interruption_received_messages_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (job, message_type)\n",
     "legendFormat": "{{ message_type }}"
    }
   ]
  },
  {
   "title": "Interruption Deleted Messages",
   "type": "timeseries",
   "description": "The number of interruption messages deleted.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    karpenter_interruption_deleted_messages_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (job)\n",
     "legendFormat": "Deleted Messages"
    }
   ]
  },
  {
   "title": "Interruption Duration",
   "type": "timeseries",
   "description": "The duration for interruption message processing.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    rate(\n      karpenter_interruption_message_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    rate(\n      karpenter_interruption_message_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    rate(\n      karpenter_interruption_message_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "description": "The depth of the work queue.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_workqueue_depth{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n) by (job)\n",
     "legendFormat": "Queue Depth"
    }
   ]
  },
  {
   "title": "Work Queue In Queue Duration",
   "type": "timeseries",
   "description": "The duration items spend in the work queue.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    irate(\n      karpenter_workqueue_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    irate(\n      karpenter_workqueue_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    irate(\n      karpenter_workqueue_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Work Queue Work Duration",
   "type": "timeseries",
   "description": "The duration to process work queue items.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    irate(\n      karpenter_workqueue_work_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    irate(\n      karpenter_workqueue_work_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    irate(\n      karpenter_workqueue_work_duration_seconds_bucket{\n        cluster=\"$cluster\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Controller Reconcile",
   "type": "timeseries",
   "description": "The ops of controller reconciliation.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  irate(\n    controller_runtime_reconcile_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (job, controller)\n",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Controller Result",
   "type": "timeseries",
   "description": "The result of controller reconciliations.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  irate(\n    controller_runtime_reconcile_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (job, result)\n",
     "legendFormat": "{{ result }}"
    }
   ]
  }
 ]
}